### ISSUE TITLE
No proxy satisfying given conditions.

### ISSUE THREAD

**Issue by lav13enrose** [2knal/random_proxies#3]
i got error output, this repo doesnt give any clues so here's the issue

Error Output 
`random_proxies.proxies.exception.NoSuchProxyError: No proxy satisfying given conditions.`

im testing it as the readme writed
`from random_proxies import random_proxy
random_proxy()`

**Comment by g0per** [comment]
```
>>> from random_proxies import random_proxy
>>> random_proxy()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python38\lib\site-packages\random_proxies\proxies\proxy.py", line 56, in random_proxy
    return pop(new_conditions)
  File "C:\Python38\lib\site-packages\random_proxies\proxies\db.py", line 22, in pop
    raise NoSuchProxyError('No proxy satisfying given conditions.')
random_proxies.proxies.exception.NoSuchProxyError: No proxy satisfying given conditions.
```

Cache server is currently inop. Workaround at #2

**Comment by lav13enrose** [comment]
Fixed by using 
`random_proxy(use_cache=False)`
thanks to @g0per 
closing this issue now
